### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by ericoc** [IsharMud/ishar-web#13]
# Use Django Permissions

I would like to translate the existing concept of using players levels to Django permissions:

- [https://docs.djangoproject.com/en/dev/topics/auth/default/#permissions-and-authorization](https://docs.djangoproject.com/en/dev/topics/auth/default/#permissions-and-authorization)

## Current

If an account has a player with a level in `settings`.`IMMORTAL_LEVELS`, that account (and that player) is considered to be an "immortal", and subsequently "`is_staff`" is "`True`" to Django.

#### Immortal Levels

`settings.IMMORTAL_LEVELS` is a dictionary with the key being the player level and the value of that key being the in-game type/rank of immortal:

```
# Player immortal levels
IMMORTAL_LEVELS = {
    26: 'God',
    25: 'Forger',
    24: 'Eternal',
    23: 'Artisan',
    22: 'Immortal',
    21: 'Consort'
}
```

- [https://github.com/IsharMud/ishar-web/blob/django/ishar/apps/player/models/__init__.py#L280-L312](https://github.com/IsharMud/ishar-web/blob/django/ishar/apps/player/models/__init__.py#L280-L312)

### Accounts

A player character's level indicating status as an "immortal"-type player is used to determine whether the users account is a staff member (`is_staff`) or otherwise an administrator allowing them to log in to the Django administration portal:

- [https://github.com/IsharMud/ishar-web/blob/django/ishar/apps/account/models/__init__.py#L204-L210](https://github.com/IsharMud/ishar-web/blob/django/ishar/apps/account/models/__init__.py#L204-L210)

If there is an immortal-type player within the users account, they are appropriately considered a staff member or administrator.

## Solution

Figure out what I do not know by repeatedly re-reading [https://docs.djangoproject.com/en/dev/topics/auth/default/#permissions-and-authorization](https://docs.djangoproject.com/en/dev/topics/auth/default/#permissions-and-authorization) to implement actual Django permissions correctly...

**Comment by Tyler-Jacob-F** [comment]
I'd be interested in potentially working with you on this. It's very possible to just move various admin permissioning in game too to just the accounts object. I.e instead of me having a level 26 character, I just have a bunch of flags on my account that represent that same permissions. Requires some thought on my end too, as it would be a pretty substantial rewrite of how permissioning works in the game as well, but would potentially make your life easier

**Comment by ericoc** [comment]
@Tyler-Jacob-F wouldn't tying the "permissions" or "god-ship"/"immortal" status to the account, rather than per player, cause problems for any immortal wanting to play a normal character though...

In that case, it seems like you would need to have a separate "mortal" account, right?

**Comment by ericoc** [comment]
https://github.com/IsharMud/ishar-web/commit/e7c598c8853f5102cd2506561183d1cfa83626b6
