### ISSUE TITLE
Historical Season Stat - Playtime

### ISSUE THREAD

**Issue by Tyler-Jacob-F** [IsharMud/ishar-web#47]
Playtime is in seconds. Can the field in Django be converted to days, hours, minutes, seconds? 

I.e. Kamala has 2,753,002

It'd be nice if it could say like 

31 days, etc, etc

**Comment by ericoc** [comment]
<img width="1552" alt="Screenshot 2024-10-07 at 9 39 10 PM" src="https://github.com/user-attachments/assets/5f9bcbf6-f91b-40d5-b9e8-b8b4b8ecd286">

**Comment by ericoc** [comment]
<img width="474" alt="Screenshot 2024-10-07 at 9 51 56 PM" src="https://github.com/user-attachments/assets/f074520f-bb33-4c89-8e04-f47eea2e9531">
